apiVersion: v1
kind: ReplicationController
metadata:
  name: httpd-rc
  labels: 
    tier: dev 
spec:
    replicas: 2
    selector: 
       app: httpd-app 
    template:
     metadata:
       name: httpd_pod 
       labels:
         app: httpd-app 
     spec:
       containers:
        - name: httpd 
          image: httpd:2.4
          ports: 
          - containerPort: 80
